//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ahshist_ws/order/v8", ConfigurationName="OrderReference.order_wsSoap")]
    public interface order_wsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ahshist_ws/order/v8/OrderSecurity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> OrderSecurityAsync(
                    string Subscriber, 
                    string SecurityType, 
                    string SecurityTypeDesc, 
                    string Isin, 
                    string Cusip, 
                    string Mic, 
                    string Sedol, 
                    string Ric, 
                    string BBId, 
                    string BBTicker, 
                    string BBMkt, 
                    string BBMktSector, 
                    string CountryIssue, 
                    string Ccy, 
                    string ShortName, 
                    string Name, 
                    OrderReference.ahs_date Maturity, 
                    OrderReference.ahs_float Strike, 
                    string PutCall, 
                    OrderReference.ahs_logical Urgent, 
                    string Message);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ahshist_ws/order/v8/OrderItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OrderReference.OrderItemResponse> OrderItemAsync(OrderReference.OrderItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ahshist_ws/order/v8/OrderMisc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> OrderMiscAsync(
                    string Subscriber, 
                    string Source, 
                    string SecurityType, 
                    OrderReference.SubscriberSet Set, 
                    string Request, 
                    string Item, 
                    string Isin, 
                    string Cusip, 
                    string Mic, 
                    string Sedol, 
                    string Ric, 
                    string BBId, 
                    string BBTicker, 
                    string BBMkt, 
                    string BBMktSector, 
                    string CountryIssue, 
                    string Ccy, 
                    string Name, 
                    OrderReference.ahs_date Maturity, 
                    OrderReference.ahs_float Strike, 
                    string PutCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ahshist_ws/order/v8/OrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<OrderReference.Status> OrderStatusAsync(int OrderId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class ahs_date
    {
        
        private System.DateTime valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class Status
    {
        
        private string codeField;
        
        private string messageField;
        
        private ahs_int securityIdField;
        
        private string createdItemField;
        
        private ahs_int relatedOrderIdField;
        
        private string existingItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ahs_int SecurityId
        {
            get
            {
                return this.securityIdField;
            }
            set
            {
                this.securityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CreatedItem
        {
            get
            {
                return this.createdItemField;
            }
            set
            {
                this.createdItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ahs_int RelatedOrderId
        {
            get
            {
                return this.relatedOrderIdField;
            }
            set
            {
                this.relatedOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExistingItem
        {
            get
            {
                return this.existingItemField;
            }
            set
            {
                this.existingItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class ahs_int
    {
        
        private int valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class SetItem
    {
        
        private string sourceField;
        
        private string nameField;
        
        private string secIdTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecIdType
        {
            get
            {
                return this.secIdTypeField;
            }
            set
            {
                this.secIdTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class SubscriberSet
    {
        
        private string nameField;
        
        private SetItem[] itemsField;
        
        private ahs_int[] securityIdsField;
        
        private ahs_logical replaceDataField;
        
        private ahs_logical mergeDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SetItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ahs_int[] SecurityIds
        {
            get
            {
                return this.securityIdsField;
            }
            set
            {
                this.securityIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ahs_logical ReplaceData
        {
            get
            {
                return this.replaceDataField;
            }
            set
            {
                this.replaceDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ahs_logical MergeData
        {
            get
            {
                return this.mergeDataField;
            }
            set
            {
                this.mergeDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class ahs_logical
    {
        
        private bool valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class OrderParameter
    {
        
        private string fieldField;
        
        private string string_valField;
        
        private ahs_float float_valField;
        
        private ahs_date date_valField;
        
        private ahs_logical logical_valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string string_val
        {
            get
            {
                return this.string_valField;
            }
            set
            {
                this.string_valField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ahs_float float_val
        {
            get
            {
                return this.float_valField;
            }
            set
            {
                this.float_valField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ahs_date date_val
        {
            get
            {
                return this.date_valField;
            }
            set
            {
                this.date_valField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ahs_logical logical_val
        {
            get
            {
                return this.logical_valField;
            }
            set
            {
                this.logical_valField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ahshist_ws/order/v8")]
    public partial class ahs_float
    {
        
        private double valField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderItem", WrapperNamespace="urn:ahshist_ws/order/v8", IsWrapped=true)]
    public partial class OrderItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=0)]
        public string Subscriber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=1)]
        public string Source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=2)]
        public string SecurityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=3)]
        public string SecurityTypeDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=4)]
        public string Item;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=5)]
        public string Isin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=6)]
        public string Cusip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=7)]
        public string Mic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=8)]
        public string Sedol;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=9)]
        public string Ric;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=10)]
        public string BBId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=11)]
        public string BBTicker;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=12)]
        public string BBMkt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=13)]
        public string BBMktSector;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=14)]
        public string CountryIssue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=15)]
        public string Ccy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=16)]
        public string ShortName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=17)]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=18)]
        public OrderReference.ahs_date Maturity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=19)]
        public OrderReference.ahs_float Strike;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=20)]
        public string PutCall;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=21)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OrderReference.OrderParameter[] Parameters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=22)]
        public string BBUnique;
        
        public OrderItemRequest()
        {
        }
        
        public OrderItemRequest(
                    string Subscriber, 
                    string Source, 
                    string SecurityType, 
                    string SecurityTypeDesc, 
                    string Item, 
                    string Isin, 
                    string Cusip, 
                    string Mic, 
                    string Sedol, 
                    string Ric, 
                    string BBId, 
                    string BBTicker, 
                    string BBMkt, 
                    string BBMktSector, 
                    string CountryIssue, 
                    string Ccy, 
                    string ShortName, 
                    string Name, 
                    OrderReference.ahs_date Maturity, 
                    OrderReference.ahs_float Strike, 
                    string PutCall, 
                    OrderReference.OrderParameter[] Parameters, 
                    string BBUnique)
        {
            this.Subscriber = Subscriber;
            this.Source = Source;
            this.SecurityType = SecurityType;
            this.SecurityTypeDesc = SecurityTypeDesc;
            this.Item = Item;
            this.Isin = Isin;
            this.Cusip = Cusip;
            this.Mic = Mic;
            this.Sedol = Sedol;
            this.Ric = Ric;
            this.BBId = BBId;
            this.BBTicker = BBTicker;
            this.BBMkt = BBMkt;
            this.BBMktSector = BBMktSector;
            this.CountryIssue = CountryIssue;
            this.Ccy = Ccy;
            this.ShortName = ShortName;
            this.Name = Name;
            this.Maturity = Maturity;
            this.Strike = Strike;
            this.PutCall = PutCall;
            this.Parameters = Parameters;
            this.BBUnique = BBUnique;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OrderItemResponse", WrapperNamespace="urn:ahshist_ws/order/v8", IsWrapped=true)]
    public partial class OrderItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ahshist_ws/order/v8", Order=0)]
        public int OrderItemResult;
        
        public OrderItemResponse()
        {
        }
        
        public OrderItemResponse(int OrderItemResult)
        {
            this.OrderItemResult = OrderItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface order_wsSoapChannel : OrderReference.order_wsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class order_wsSoapClient : System.ServiceModel.ClientBase<OrderReference.order_wsSoap>, OrderReference.order_wsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public order_wsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(order_wsSoapClient.GetBindingForEndpoint(endpointConfiguration), order_wsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public order_wsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(order_wsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public order_wsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(order_wsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public order_wsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> OrderSecurityAsync(
                    string Subscriber, 
                    string SecurityType, 
                    string SecurityTypeDesc, 
                    string Isin, 
                    string Cusip, 
                    string Mic, 
                    string Sedol, 
                    string Ric, 
                    string BBId, 
                    string BBTicker, 
                    string BBMkt, 
                    string BBMktSector, 
                    string CountryIssue, 
                    string Ccy, 
                    string ShortName, 
                    string Name, 
                    OrderReference.ahs_date Maturity, 
                    OrderReference.ahs_float Strike, 
                    string PutCall, 
                    OrderReference.ahs_logical Urgent, 
                    string Message)
        {
            return base.Channel.OrderSecurityAsync(Subscriber, SecurityType, SecurityTypeDesc, Isin, Cusip, Mic, Sedol, Ric, BBId, BBTicker, BBMkt, BBMktSector, CountryIssue, Ccy, ShortName, Name, Maturity, Strike, PutCall, Urgent, Message);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrderReference.OrderItemResponse> OrderReference.order_wsSoap.OrderItemAsync(OrderReference.OrderItemRequest request)
        {
            return base.Channel.OrderItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrderReference.OrderItemResponse> OrderItemAsync(
                    string Subscriber, 
                    string Source, 
                    string SecurityType, 
                    string SecurityTypeDesc, 
                    string Item, 
                    string Isin, 
                    string Cusip, 
                    string Mic, 
                    string Sedol, 
                    string Ric, 
                    string BBId, 
                    string BBTicker, 
                    string BBMkt, 
                    string BBMktSector, 
                    string CountryIssue, 
                    string Ccy, 
                    string ShortName, 
                    string Name, 
                    OrderReference.ahs_date Maturity, 
                    OrderReference.ahs_float Strike, 
                    string PutCall, 
                    OrderReference.OrderParameter[] Parameters, 
                    string BBUnique)
        {
            OrderReference.OrderItemRequest inValue = new OrderReference.OrderItemRequest();
            inValue.Subscriber = Subscriber;
            inValue.Source = Source;
            inValue.SecurityType = SecurityType;
            inValue.SecurityTypeDesc = SecurityTypeDesc;
            inValue.Item = Item;
            inValue.Isin = Isin;
            inValue.Cusip = Cusip;
            inValue.Mic = Mic;
            inValue.Sedol = Sedol;
            inValue.Ric = Ric;
            inValue.BBId = BBId;
            inValue.BBTicker = BBTicker;
            inValue.BBMkt = BBMkt;
            inValue.BBMktSector = BBMktSector;
            inValue.CountryIssue = CountryIssue;
            inValue.Ccy = Ccy;
            inValue.ShortName = ShortName;
            inValue.Name = Name;
            inValue.Maturity = Maturity;
            inValue.Strike = Strike;
            inValue.PutCall = PutCall;
            inValue.Parameters = Parameters;
            inValue.BBUnique = BBUnique;
            return ((OrderReference.order_wsSoap)(this)).OrderItemAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<int> OrderMiscAsync(
                    string Subscriber, 
                    string Source, 
                    string SecurityType, 
                    OrderReference.SubscriberSet Set, 
                    string Request, 
                    string Item, 
                    string Isin, 
                    string Cusip, 
                    string Mic, 
                    string Sedol, 
                    string Ric, 
                    string BBId, 
                    string BBTicker, 
                    string BBMkt, 
                    string BBMktSector, 
                    string CountryIssue, 
                    string Ccy, 
                    string Name, 
                    OrderReference.ahs_date Maturity, 
                    OrderReference.ahs_float Strike, 
                    string PutCall)
        {
            return base.Channel.OrderMiscAsync(Subscriber, Source, SecurityType, Set, Request, Item, Isin, Cusip, Mic, Sedol, Ric, BBId, BBTicker, BBMkt, BBMktSector, CountryIssue, Ccy, Name, Maturity, Strike, PutCall);
        }
        
        public System.Threading.Tasks.Task<OrderReference.Status> OrderStatusAsync(int OrderId)
        {
            return base.Channel.OrderStatusAsync(OrderId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.order_wsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.order_wsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.order_wsSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://release20/ahshist_ws/order_v8.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.order_wsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://release20/ahshist_ws/order_v8.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            order_wsSoap,
            
            order_wsSoap12,
        }
    }
}
